In [2]:
import pandas as pd

# Load dataset
file_path = "data_obat.xlsx"
df = pd.read_excel(file_path)
df

,id_name_assist,name_master_erp,generic_flag,Bahan Aktif/Kandungan/Komposisi,Indikasi,Dosis Penggunaan,Penyajian,Golongan Obat,Kontraindikasi,Efek Samping,Cara Kerja Obat,Golongan Obat (Obat bebas/Obat resep),Harga
0,BYE BYE FEVER PCS DEWASA,BYEBYE FEVER DEWASA SACHET,BRN,Gel pendingin berbasis hidrogel,"Meredakan demam, sakit kepala, dan rasa tidak ...",1 plester setiap 8 - 10 jam,Ditempelkan langsung pada Dahi,Alat kesehatan,"Alergi terhadap bahan gel, kulit iritasi/luka","Iritasi ringan pada kulit, reaksi alergi",Menurunkan suhu tubuh dengan efek pendingin hi...,Obat bebas,Rp. 17.000 - Rp. 22.000 per sachet
1,ONEMED BLOOD LANCET 28G- PCS -,ONEMED BLOOD LANCET 28G BOX 100 PCS,BRN,"Jarum lancet steril sekali pakai, gauge 28G, b...","Pengambilan sampel darah (diabetes, kolestrol,...",Sekali pakai tiap pengambilan sampel darah,Jarum steril sekali pakai yang digunakan bersa...,Alat kesehatan sekali pakai,Hindari penggunaan di kulit berdarah berat ata...,"Risiko minimal, bisa menyebabkan nyeri ringan ...",Menusuk kulit ujung jari untuk mengambil sampe...,Obat bebas,Rp. 8.700 - Rp. 12.000 per box isi 100 pcs
2,FIESTA MAX DOTTEDB 3`S BUAH -,FIESTA KONDOM MAX DOTTED BOX 3 PCS,BRN,Natural rubber latex,Pencegahan kehamilan & infeksi menular seksual...,1 kondom sekali pakai sesuai kebutuhan (setiap...,Dipakai oleh pria pada alat vital sebelum berh...,Alat kontrasepsi sekali pakai (produk konsumen),"Alergi latex, kulit iritasi di area genital; t...",hentikan pemakaian jika terjadi iritasi atau r...,Mencegah kehamilan dan IMS lewat penghalang fi...,Obat bebas,Rp. 28.000 Isi 3 pcs
3,BETADINE SALEP PCS 5GR,BETADINE SALEP TUBE 10 GRAM,BRN,Povidone‑iodine 10%,"Digunakan untuk luka bakar ringan, luka sayat,...","Oles 1–2 kali sehari pada permukaan luka, sesu...","Setelah membersihkan luka, oleskan salep secuk...",Obat antiseptik oles,Alergi terhadap iodine atau komponen lainnya; ...,"Bisa menyebabkan iritasi lokal, rasa panas, ga...",Bekerja dengan membunuh dan menghambat pertumb...,Obat bebas,Rp. 25.000 - Rp. 33.000 per tube
4,SUSU PRENAGEN MOMMY COKLAT KOTAK 200G,PRENAGEN MOMMY SUSU IBU HAMIL RASA COKLAT 200 ...,BRN,"Susu skim bubuk, susu bubuk full cream, sukros...",Nutrisi tambahan untuk ibu hamil,2 kali sehari (3 sendok makan/45 gr per saji)\t,"Campur bubuk dengan 180 ml air hangat, aduk hi...",Suplemen,"Alergi terhadap kandungan, konsultasikan jika ...","Jarang menimbulkan efek samping, tetapi dapat ...",Membantu memenuhi kebutuhan nutrisi ibu dan ja...,Obat bebas\t,Rp52.914 per 200 Gram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,PARACETAMOL SYRUP HOLI 60.00 ML FLASH -,PARACETAMOL HOLI 120 MG/5 ML SYRUP 60 ML,Generic,Cetirizine 10 mg,"Rhinitis alergi, urtikaria",Dewasa: 10 mg/hari,Tablet,Antihistamin,Hipersensitivitas,"Kantuk, mulut kering",Blok reseptor H1 histamin,Obat bebas terbatas,"Rp3.502,-/strip"
539,GENTAMICIN 0.3% CENDO SALEP MATA TUB -,"CENDO GENTAMYCIN 3,5 GRAM SALEP MATA",Generic,"Sodium Chloride 0,9% Infus 500 ml","Rehidrasi, pelarut obat infus",Sesuai kebutuhan medis,Larutan infus 500 ml,Larutan elektrolit,Gagal jantung kongestif berat,"Hipernatremia, overhidrasi",Menggantikan cairan/elektrolit,Obat resep,"Rp6.000,-/botol"
540,CETIRIZIN 10 MG NOVELL TAB -,CETIRIZINE NOVELL 10 MG TABLET,Generic,Metamizole Sodium 500 mg,"Nyeri sedang-berat, demam",Dewasa: 500–1000 mg tiap 6–8 jam,Tablet,Analgesik-antipiretik,Agranulositosis,"Reaksi alergi, hipotensi",Menghambat sintesis prostaglandin,Obat resep,"Rp6.000,-/strip"
541,"SODIUM CHLORIDE 0,9% INFUS 4,5 G/500 ML, EMJEB...",SODIUM CHLORIDE 0.9% EMJEBE 500 ML BOTOL,Generic,"Sodium Chloride 0,9%","Rehidrasi, pelarut obat infus",Sesuai kebutuhan medis,Larutan infus 500 ml,Larutan elektrolit,Gagal jantung kongestif berat,"Hipernatremia, overhidrasi",Menggantikan cairan/elektrolit,Obat resep,"Rp6.000,-/botol"
542,2A METAMIZOL SODIUM TABLET TABLET 500 MG,METAMIZOLE SODIUM CORSA 500 MG TABLET,Generic,Metamizole Sodium 500 mg,"Nyeri sedang-berat, demam",Dewasa: 500–1000 mg tiap 6–8 jam,Tablet,Analgesik-antipiretik,Agranulositosis,"Reaksi alergi, hipotensi",Menghambat sintesis prostaglandin,Obat resep,"Rp6.000,-/strip"

In [3]:
import re

# Isi NaN dengan string kosong
for col in df.columns:
    df[col] = df[col].fillna("")

# Fungsi cleaning

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"\\n", " ", text)
    text = re.sub(r"[^a-zA-Z0-9À-ÿ ]", " ", text)
    text = re.sub(r"\\s+", " ", text).strip()
    return text

# Gabungkan semua informasi menjadi satu dokumen

df["combined_text"] = df.apply(lambda row: f'''
Nama Obat: {row['name_master_erp']}
Kategori: {row['Golongan Obat']}
Kandungan: {row['Bahan Aktif/Kandungan/Komposisi']}
Indikasi: {row['Indikasi']}
Dosis: {row['Dosis Penggunaan']}
Penyajian: {row['Penyajian']}
Kontraindikasi: {row['Kontraindikasi']}
Efek Samping: {row['Efek Samping']}
Cara Kerja: {row['Cara Kerja Obat']}
Harga: {row['Harga']}
''', axis=1)

# Cleaning

df["combined_text"] = df["combined_text"].apply(clean_text)

df[["name_master_erp", "combined_text"]].head()

,name_master_erp,combined_text
0,BYEBYE FEVER DEWASA SACHET,nama obat byebye fever dewasa sachet kategori...
1,ONEMED BLOOD LANCET 28G BOX 100 PCS,nama obat onemed blood lancet 28g box 100 pcs...
2,FIESTA KONDOM MAX DOTTED BOX 3 PCS,nama obat fiesta kondom max dotted box 3 pcs ...
3,BETADINE SALEP TUBE 10 GRAM,nama obat betadine salep tube 10 gram kategor...
4,PRENAGEN MOMMY SUSU IBU HAMIL RASA COKLAT 200 ...,nama obat prenagen mommy susu ibu hamil rasa ...

In [4]:
from sentence_transformers import SentenceTransformer

# Load embedding model
embedding_model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

# Membuat embedding
texts = df["combined_text"].tolist()
embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Shape embedding:", embeddings.shape)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Shape embedding: (543, 384)

In [ ]:
!pip install faiss-cpu

In [8]:
import faiss
import numpy as np

# Dimensi embedding
embedding_dimension = embeddings.shape[1]

# Membuat index FAISS
index = faiss.IndexFlatL2(embedding_dimension)

# Tambahkan embedding ke index
index.add(np.array(embeddings, dtype=np.float32))

print("Jumlah vector dalam index:", index.ntotal)

Jumlah vector dalam index: 543

In [9]:
# Simpan index
faiss.write_index(index, "faiss_index.index")

# Simpan dataframe

df.to_pickle("data_obat.pkl")

print("FAISS index berhasil disimpan")

FAISS index berhasil disimpan

In [10]:
import faiss
import pandas as pd

# Load index
index = faiss.read_index("faiss_index.index")

# Load dataframe

df = pd.read_pickle("data_obat.pkl")

In [11]:
df

,id_name_assist,name_master_erp,generic_flag,Bahan Aktif/Kandungan/Komposisi,Indikasi,Dosis Penggunaan,Penyajian,Golongan Obat,Kontraindikasi,Efek Samping,Cara Kerja Obat,Golongan Obat (Obat bebas/Obat resep),Harga,combined_text
0,BYE BYE FEVER PCS DEWASA,BYEBYE FEVER DEWASA SACHET,BRN,Gel pendingin berbasis hidrogel,"Meredakan demam, sakit kepala, dan rasa tidak ...",1 plester setiap 8 - 10 jam,Ditempelkan langsung pada Dahi,Alat kesehatan,"Alergi terhadap bahan gel, kulit iritasi/luka","Iritasi ringan pada kulit, reaksi alergi",Menurunkan suhu tubuh dengan efek pendingin hi...,Obat bebas,Rp. 17.000 - Rp. 22.000 per sachet,nama obat byebye fever dewasa sachet kategori...
1,ONEMED BLOOD LANCET 28G- PCS -,ONEMED BLOOD LANCET 28G BOX 100 PCS,BRN,"Jarum lancet steril sekali pakai, gauge 28G, b...","Pengambilan sampel darah (diabetes, kolestrol,...",Sekali pakai tiap pengambilan sampel darah,Jarum steril sekali pakai yang digunakan bersa...,Alat kesehatan sekali pakai,Hindari penggunaan di kulit berdarah berat ata...,"Risiko minimal, bisa menyebabkan nyeri ringan ...",Menusuk kulit ujung jari untuk mengambil sampe...,Obat bebas,Rp. 8.700 - Rp. 12.000 per box isi 100 pcs,nama obat onemed blood lancet 28g box 100 pcs...
2,FIESTA MAX DOTTEDB 3`S BUAH -,FIESTA KONDOM MAX DOTTED BOX 3 PCS,BRN,Natural rubber latex,Pencegahan kehamilan & infeksi menular seksual...,1 kondom sekali pakai sesuai kebutuhan (setiap...,Dipakai oleh pria pada alat vital sebelum berh...,Alat kontrasepsi sekali pakai (produk konsumen),"Alergi latex, kulit iritasi di area genital; t...",hentikan pemakaian jika terjadi iritasi atau r...,Mencegah kehamilan dan IMS lewat penghalang fi...,Obat bebas,Rp. 28.000 Isi 3 pcs,nama obat fiesta kondom max dotted box 3 pcs ...
3,BETADINE SALEP PCS 5GR,BETADINE SALEP TUBE 10 GRAM,BRN,Povidone‑iodine 10%,"Digunakan untuk luka bakar ringan, luka sayat,...","Oles 1–2 kali sehari pada permukaan luka, sesu...","Setelah membersihkan luka, oleskan salep secuk...",Obat antiseptik oles,Alergi terhadap iodine atau komponen lainnya; ...,"Bisa menyebabkan iritasi lokal, rasa panas, ga...",Bekerja dengan membunuh dan menghambat pertumb...,Obat bebas,Rp. 25.000 - Rp. 33.000 per tube,nama obat betadine salep tube 10 gram kategor...
4,SUSU PRENAGEN MOMMY COKLAT KOTAK 200G,PRENAGEN MOMMY SUSU IBU HAMIL RASA COKLAT 200 ...,BRN,"Susu skim bubuk, susu bubuk full cream, sukros...",Nutrisi tambahan untuk ibu hamil,2 kali sehari (3 sendok makan/45 gr per saji)\t,"Campur bubuk dengan 180 ml air hangat, aduk hi...",Suplemen,"Alergi terhadap kandungan, konsultasikan jika ...","Jarang menimbulkan efek samping, tetapi dapat ...",Membantu memenuhi kebutuhan nutrisi ibu dan ja...,Obat bebas\t,Rp52.914 per 200 Gram,nama obat prenagen mommy susu ibu hamil rasa ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,PARACETAMOL SYRUP HOLI 60.00 ML FLASH -,PARACETAMOL HOLI 120 MG/5 ML SYRUP 60 ML,Generic,Cetirizine 10 mg,"Rhinitis alergi, urtikaria",Dewasa: 10 mg/hari,Tablet,Antihistamin,Hipersensitivitas,"Kantuk, mulut kering",Blok reseptor H1 histamin,Obat bebas terbatas,"Rp3.502,-/strip",nama obat paracetamol holi 120 mg 5 ml syrup ...
539,GENTAMICIN 0.3% CENDO SALEP MATA TUB -,"CENDO GENTAMYCIN 3,5 GRAM SALEP MATA",Generic,"Sodium Chloride 0,9% Infus 500 ml","Rehidrasi, pelarut obat infus",Sesuai kebutuhan medis,Larutan infus 500 ml,Larutan elektrolit,Gagal jantung kongestif berat,"Hipernatremia, overhidrasi",Menggantikan cairan/elektrolit,Obat resep,"Rp6.000,-/botol",nama obat cendo gentamycin 3 5 gram salep mat...
540,CETIRIZIN 10 MG NOVELL TAB -,CETIRIZINE NOVELL 10 MG TABLET,Generic,Metamizole Sodium 500 mg,"Nyeri sedang-berat, demam",Dewasa: 500–1000 mg tiap 6–8 jam,Tablet,Analgesik-antipiretik,Agranulositosis,"Reaksi alergi, hipotensi",Menghambat sintesis prostaglandin,Obat resep,"Rp6.000,-/strip",nama obat cetirizine novell 10 mg tablet kate...
541,"SODIUM CHLORIDE 0,9% INFUS 4,5 G/500 ML, EMJEB...",SODIUM CHLORIDE 0.9% EMJEBE 500 ML BOTOL,Generic,"Sodium Chloride 0,9%","Rehidrasi, pelarut obat infus",Sesuai kebutuhan medis,Larutan infus 500 ml,Larutan elektrolit,Gagal jantung kongestif berat,"Hipernatremia, overhidrasi",Menggantikan cairan/elektrolit,Obat resep,"Rp6.000,-/botol",nama obat sodium chloride 0 9 emjebe 500 ml ...
542,2A METAMIZOL SODIUM TABLET TABLET 500 MG,METAMIZOLE SODIUM CORSA 500 MG TABLET,Generic,Metamizole Sodium 500 mg,"Nyeri sedang-berat, demam",Dewasa: 500–1000 mg tiap 6–8 jam,Tablet,Analgesik-antipiretik,Agranulositosis,"Reaksi alergi, hipotensi",Menghambat sintesis prostaglandin,Obat resep,"Rp6.000,-/strip",nama obat metamizole sodium corsa 500 mg tabl...

In [12]:
import numpy as np

# Fungsi retrieval

def retrieve_documents(query, top_k=3):
    # Embedding query
    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    )

    # Search ke FAISS
    distances, indices = index.search(
        np.array(query_embedding, dtype=np.float32),
        top_k
    )

    results = []

    for idx in indices[0]:
        results.append({
            "nama_obat": df.iloc[idx]["name_master_erp"],
            "document": df.iloc[idx]["combined_text"]
        })

    return results

In [14]:
query = "pencegah kehamilan"

results = retrieve_documents(query)

for i, res in enumerate(results):
    print(f"\\n=== HASIL {i+1} ===")
    print("Nama Obat:", res["nama_obat"])
    print(res["document"][:500])

\n=== HASIL 1 ===
Nama Obat: NOVA-T COOPER IUD
nama obat  nova t cooper iud kategori  alat kontrasepsi dalam rahim  medical device  bukan obat oral  kandungan  inti plastik  polyethylene  berserat tembaga dan perak  kawat tembaga  380 mm  permukaan aktif indikasi  kb jangka panjang untuk wanita yang ingin menunda cegah kehamilan selama 5 10 tahun dosis  pemasangan satu kali oleh tenaga profesional  tidak perlu dibongkar tiap hari penyajian  dipasang dokter kandungan di rongga uterus setelah pemeriksaan persiapan  biasanya saat menstruasi ata
\n=== HASIL 2 ===
Nama Obat: SENSITIF COMPACT TEST KEHAMILAN
nama obat  sensitif compact test kehamilan kategori  alat kesehatan  kandungan  plastik  strip reagen dengan antibodi hcg  indikasi  mendeteksi kehamilan melalui urin  dosis  1 kali pemakaian  penyajian  celupkan ujung strip ke urin atau teteskan urin ke area tes sesuai petunjuk  kontraindikasi  jangan digunakan setelah kedaluwarsa atau pada kemasan rusak  efek samping  hasil palsu positif negatif jika digunakan tidak sesuai instruksi  cara kerja  mendeteksi hormon hcg dalam urin sebagai indikat
\n=== HASIL 3 ===
Nama Obat: SENSITIF COMPACT TEST KEHAMILAN
nama obat  sensitif compact test kehamilan kategori  alat kesehatan  kandungan  plastik  strip reagen dengan antibodi hcg  indikasi  mendeteksi kehamilan melalui urin  dosis  1 kali pemakaian  penyajian  celupkan ujung strip ke urin atau teteskan urin ke area tes sesuai petunjuk  kontraindikasi  jangan digunakan setelah kedaluwarsa atau pada kemasan rusak  efek samping  hasil palsu positif negatif jika digunakan tidak sesuai instruksi  cara kerja  mendeteksi hormon hcg dalam urin sebagai indikat

# Ini untuk Save Model, dan bisa dicoba untuk deploy model

In [15]:
# Save embedding model
embedding_model.save("models/embedding_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

# Jika Menggunakan Llama

In [ ]:
from transformers import pipeline

# Load local LLM
llm = pipeline(
    "text-generation",
    model="microsoft/Phi-3-mini-4k-instruct",
    device_map="auto"
)


def ask_local_llm(query):
    retrieved_docs = retrieve_documents(query, top_k=3)

    context = "\\n\\n".join([
        doc["document"] for doc in retrieved_docs
    ])

    prompt = f'''
Kamu adalah AI Agent Farmasi.

Berikut data obat:
{context}

Pertanyaan:
{query}

Jawaban:
'''

    result = llm(
        prompt,
        max_new_tokens=300,
        do_sample=True,
        temperature=0.3
    )

    return result[0]["generated_text"]

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu and disk.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [ ]:
question = "Apa obat yang cocok untuk luka bakar ringan?"

answer = ask_local_llm(question)

print(answer)

Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)